export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER'
export const FETCH_STICKY_NOTES = 'FETCH_STICKY_NOTES';
export const ADD_STICKY_NOTES = 'ADD_STICKY_NOTES';
export const CANCEL_STICKY_NOTES = 'CANCEL_STICKY_NOTES';
export const SAVE_STICKY_NOTE = 'SAVE_STICKY_NOTE';
export const ERROR_STICKY_NOTE ='ERROR_STICKY_NOTE';
export const INPUT_CHANGE_STICKY_NOTE = 'INPUT_CHANGE_STICKY_NOTE';
